"2024-02-25 20:39:13,609 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-25 20:39:13,610 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-25 20:39:13,610 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-25 20:39:17,192 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-25 20:39:17,285 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-25 20:39:21,162 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850425 is handled. Duration 388 ms by bot id=6249292999"
"2024-02-25 20:39:33,219 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-25 20:39:33,219 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-25 20:39:33,219 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-25 20:39:36,792 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-25 20:39:36,879 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-25 20:39:38,731 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850426 is handled. Duration 447 ms by bot id=6249292999"
"2024-02-25 20:39:40,331 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850427 is handled. Duration 122 ms by bot id=6249292999"
"2024-02-25 20:39:51,626 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850428 is handled. Duration 149 ms by bot id=6249292999"
"2024-02-25 21:06:47,498 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850429 is handled. Duration 510 ms by bot id=6249292999"
"2024-02-26 23:05:01,940 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-26 23:05:02,032 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:05:21,401 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850430 is handled. Duration 416 ms by bot id=6249292999"
"2024-02-26 23:05:23,389 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850431 is not handled. Duration 1 ms by bot id=6249292999"
"2024-02-26 23:05:24,571 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850432 is handled. Duration 229 ms by bot id=6249292999"
"2024-02-26 23:06:18,697 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850433 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-26 23:08:52,924 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850434 is handled. Duration 326 ms by bot id=6249292999"
"2024-02-26 23:08:55,876 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850435 is handled. Duration 238 ms by bot id=6249292999"
"2024-02-26 23:09:43,524 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-26 23:09:43,525 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:09:43,525 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-26 23:09:46,966 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-26 23:09:47,054 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:14:20,150 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850436 is handled. Duration 356 ms by bot id=6249292999"
"2024-02-26 23:14:22,498 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850437 is handled. Duration 175 ms by bot id=6249292999"
"2024-02-26 23:48:27,063 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850438 is not handled. Duration 2 ms by bot id=6249292999"
"2024-02-26 23:48:45,171 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-26 23:48:45,172 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:48:45,173 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-26 23:48:52,535 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-26 23:48:52,627 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:48:53,647 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850439 is handled. Duration 384 ms by bot id=6249292999"
"2024-02-26 23:49:31,096 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-26 23:49:31,097 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:49:31,097 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-26 23:49:34,857 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-26 23:49:34,939 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-26 23:49:39,246 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850440 is handled. Duration 334 ms by bot id=6249292999"
"2024-02-26 23:49:41,348 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850441 is handled. Duration 181 ms by bot id=6249292999"
"2024-02-27 00:03:54,335 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:03:54,341 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:03:54,341 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:03:59,629 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:03:59,722 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:04:00,846 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850443 is handled. Duration 298 ms by bot id=6249292999"
"2024-02-27 00:04:04,151 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850444 is handled. Duration 205 ms by bot id=6249292999"
"2024-02-27 00:04:14,534 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850445 is handled. Duration 126 ms by bot id=6249292999"
"2024-02-27 00:04:48,264 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850446 is handled. Duration 328 ms by bot id=6249292999"
"2024-02-27 00:06:15,715 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850447 is handled. Duration 310 ms by bot id=6249292999"
"2024-02-27 00:06:17,474 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850448 is handled. Duration 193 ms by bot id=6249292999"
"2024-02-27 00:06:23,531 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:06:23,532 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:06:23,533 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:06:29,164 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:06:29,270 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:06:30,010 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850449 is handled. Duration 330 ms by bot id=6249292999"
"2024-02-27 00:06:43,513 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:06:43,515 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:06:43,516 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:06:47,374 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:06:47,452 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:06:48,978 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850451 is handled. Duration 308 ms by bot id=6249292999"
"2024-02-27 00:06:50,656 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850452 is handled. Duration 158 ms by bot id=6249292999"
"2024-02-27 00:06:53,497 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850453 is handled. Duration 113 ms by bot id=6249292999"
"2024-02-27 00:12:35,665 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:12:35,758 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:12:44,396 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850454 is handled. Duration 282 ms by bot id=6249292999"
"2024-02-27 00:12:50,077 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850455 is handled. Duration 179 ms by bot id=6249292999"
"2024-02-27 00:24:15,012 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:24:15,015 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:24:15,015 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:24:19,512 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:24:19,626 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:24:20,264 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850456 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 00:24:20,264 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850456 by bot id=6249292999\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'str'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 197, in how_long_design\n    await query.message.answer(how_long_design_text+feedback_text, reply_markup=proj_design_feedback_buttons())\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'str'"
"2024-02-27 00:24:23,104 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850457 is not handled. Duration 1 ms by bot id=6249292999"
"2024-02-27 00:24:23,104 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850457 by bot id=6249292999\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'str'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 197, in how_long_design\n    await query.message.answer(how_long_design_text+feedback_text, reply_markup=proj_design_feedback_buttons())\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'str'"
"2024-02-27 00:24:53,261 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:24:53,261 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:24:53,262 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:24:57,104 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:24:57,197 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:24:59,526 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850458 is handled. Duration 306 ms by bot id=6249292999"
"2024-02-27 00:27:04,103 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:27:04,103 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:27:04,104 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:27:07,751 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:27:07,844 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:27:19,114 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850459 is handled. Duration 350 ms by bot id=6249292999"
"2024-02-27 00:27:20,738 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850460 is handled. Duration 154 ms by bot id=6249292999"
"2024-02-27 00:37:39,905 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:37:39,906 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:37:39,906 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 00:37:43,785 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 00:37:43,874 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:37:46,841 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850461 is handled. Duration 334 ms by bot id=6249292999"
"2024-02-27 00:37:50,770 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850462 is handled. Duration 407 ms by bot id=6249292999"
"2024-02-27 00:37:55,759 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850463 is handled. Duration 3455 ms by bot id=6249292999"
"2024-02-27 00:38:00,052 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850464 is handled. Duration 321 ms by bot id=6249292999"
"2024-02-27 00:38:05,373 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850465 is handled. Duration 3747 ms by bot id=6249292999"
"2024-02-27 00:47:53,235 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 00:47:53,238 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 00:47:53,238 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:25:08,575 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:25:08,665 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:25:20,407 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850466 is handled. Duration 3946 ms by bot id=6249292999"
"2024-02-27 01:25:29,522 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850467 is handled. Duration 99 ms by bot id=6249292999"
"2024-02-27 01:25:33,111 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850468 is not handled. Duration 80 ms by bot id=6249292999"
"2024-02-27 01:25:33,111 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850468 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 237, in send_request\n    await message.answer(f\"\u042d\u0442\u043e \u0441\u0444\u0435\u0440\u0430 \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u0438 - {info.field_activity}, \u0430 \u044d\u0442\u043e \u0441 \u0447\u0435\u043c \u043d\u0443\u0436\u043d\u0430 \u043f\u043e\u043c\u043e\u0449\u044c - {info.which_help}\")\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'"
"2024-02-27 01:25:59,447 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 01:25:59,448 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:25:59,448 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:26:02,984 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:26:03,094 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:26:11,370 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850469 is handled. Duration 3845 ms by bot id=6249292999"
"2024-02-27 01:26:16,237 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850470 is handled. Duration 96 ms by bot id=6249292999"
"2024-02-27 01:26:18,388 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850471 is handled. Duration 209 ms by bot id=6249292999"
"2024-02-27 01:26:24,096 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850472 is handled. Duration 3791 ms by bot id=6249292999"
"2024-02-27 01:26:27,098 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850473 is handled. Duration 138 ms by bot id=6249292999"
"2024-02-27 01:26:31,069 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850474 is not handled. Duration 195 ms by bot id=6249292999"
"2024-02-27 01:26:31,069 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850474 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 601\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 238, in send_request\n    await message.answer(send_request_text, reply_markup=biz_consultation_buttons())\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 601"
"2024-02-27 01:29:52,486 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 01:29:52,487 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:29:52,487 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:29:55,943 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:29:56,033 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:30:03,755 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850475 is handled. Duration 4097 ms by bot id=6249292999"
"2024-02-27 01:30:05,378 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850476 is handled. Duration 199 ms by bot id=6249292999"
"2024-02-27 01:30:06,611 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850477 is not handled. Duration 251 ms by bot id=6249292999"
"2024-02-27 01:30:06,611 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850477 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 601\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 238, in send_request\n    await message.answer(send_request_text, reply_markup=biz_consultation_buttons())\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Can't find end of Bold entity at byte offset 601"
"2024-02-27 01:37:06,236 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 01:37:06,239 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:37:06,239 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:37:10,140 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:37:10,231 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:37:23,999 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850478 is handled. Duration 3786 ms by bot id=6249292999"
"2024-02-27 01:37:25,604 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850479 is handled. Duration 98 ms by bot id=6249292999"
"2024-02-27 01:37:26,901 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850480 is handled. Duration 211 ms by bot id=6249292999"
"2024-02-27 01:43:54,239 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 01:43:54,240 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:43:54,240 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:43:57,633 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:43:57,715 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:47:41,377 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 01:47:41,378 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:47:41,378 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 01:47:45,081 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 01:47:45,158 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 01:48:51,113 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850481 is handled. Duration 3834 ms by bot id=6249292999"
"2024-02-27 01:48:52,719 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850482 is handled. Duration 122 ms by bot id=6249292999"
"2024-02-27 01:48:53,904 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850483 is handled. Duration 275 ms by bot id=6249292999"
"2024-02-27 02:07:14,579 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:07:14,582 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:07:14,583 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:12:10,637 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 02:12:10,638 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 158, in <module>"
"2024-02-27 02:12:10,638 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 02:12:10,638 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 02:12:10,638 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 02:12:10,639 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 02:12:10,639 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 02:12:10,640 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 139, in start_bot"
"2024-02-27 02:12:10,640 - [ERROR] - STDERR - (bot_logger.py).write(20) - dp.callback_query.answer(my_social_network, MyCallback.filter(F.foo == 'my_social_network'))"
"2024-02-27 02:12:10,640 - [ERROR] - STDERR - (bot_logger.py).write(20) - AttributeError"
"2024-02-27 02:12:10,640 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 02:12:10,640 - [ERROR] - STDERR - (bot_logger.py).write(20) - 'TelegramEventObserver' object has no attribute 'answer'"
"2024-02-27 02:12:10,745 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f767be89270>"
"2024-02-27 02:12:10,745 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f767be96920>, 7272.967279825)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7f767be8ab30>"
"2024-02-27 02:13:21,467 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 02:13:21,470 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 158, in <module>"
"2024-02-27 02:13:21,471 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 02:13:21,471 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 02:13:21,472 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 02:13:21,472 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 02:13:21,473 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 02:13:21,473 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 139, in start_bot"
"2024-02-27 02:13:21,474 - [ERROR] - STDERR - (bot_logger.py).write(20) - dp.callback_query.answer(my_social_network, MyCallback.filter(F.foo == 'my_social_network'))"
"2024-02-27 02:13:21,474 - [ERROR] - STDERR - (bot_logger.py).write(20) - AttributeError"
"2024-02-27 02:13:21,474 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 02:13:21,474 - [ERROR] - STDERR - (bot_logger.py).write(20) - 'TelegramEventObserver' object has no attribute 'answer'"
"2024-02-27 02:13:21,568 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f7ea32809a0>"
"2024-02-27 02:13:21,569 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f7ea11a6980>, 7343.7872876)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7f7ea117f580>"
"2024-02-27 02:14:15,857 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:14:15,948 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:14:18,892 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850485 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 02:15:01,586 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:15:01,586 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:15:01,587 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:15:05,203 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:15:05,283 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:15:07,199 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850486 is handled. Duration 400 ms by bot id=6249292999"
"2024-02-27 02:15:12,316 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850487 is handled. Duration 3582 ms by bot id=6249292999"
"2024-02-27 02:15:16,414 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850488 is handled. Duration 110 ms by bot id=6249292999"
"2024-02-27 02:15:17,803 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850489 is handled. Duration 206 ms by bot id=6249292999"
"2024-02-27 02:15:20,210 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850490 is handled. Duration 127 ms by bot id=6249292999"
"2024-02-27 02:15:25,958 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850491 is handled. Duration 3665 ms by bot id=6249292999"
"2024-02-27 02:15:29,347 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850492 is handled. Duration 98 ms by bot id=6249292999"
"2024-02-27 02:15:30,875 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850493 is handled. Duration 195 ms by bot id=6249292999"
"2024-02-27 02:15:34,882 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850494 is handled. Duration 147 ms by bot id=6249292999"
"2024-02-27 02:15:39,266 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850495 is not handled. Duration 1 ms by bot id=6249292999"
"2024-02-27 02:15:42,001 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850496 is handled. Duration 101 ms by bot id=6249292999"
"2024-02-27 02:16:20,676 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:16:20,677 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:16:20,677 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:16:56,055 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:16:56,148 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:16:59,184 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850498 is handled. Duration 283 ms by bot id=6249292999"
"2024-02-27 02:17:05,304 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850499 is handled. Duration 105 ms by bot id=6249292999"
"2024-02-27 02:18:35,016 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:18:35,017 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:18:35,017 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:18:38,665 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:18:38,755 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:18:45,734 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850500 is handled. Duration 373 ms by bot id=6249292999"
"2024-02-27 02:18:51,545 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:18:51,546 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:18:51,546 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:20:43,598 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:20:43,683 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:20:52,049 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850501 is handled. Duration 312 ms by bot id=6249292999"
"2024-02-27 02:22:29,495 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850502 is handled. Duration 380 ms by bot id=6249292999"
"2024-02-27 02:31:05,843 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:31:05,847 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:31:05,847 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:31:09,453 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:31:09,533 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:31:37,167 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850503 is handled. Duration 376 ms by bot id=6249292999"
"2024-02-27 02:31:42,744 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850504 is handled. Duration 3486 ms by bot id=6249292999"
"2024-02-27 02:33:07,507 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 02:33:07,509 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:33:07,509 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 02:33:11,741 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 02:33:11,824 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 02:33:14,414 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850505 is handled. Duration 385 ms by bot id=6249292999"
"2024-02-27 02:33:19,998 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850506 is handled. Duration 3506 ms by bot id=6249292999"
"2024-02-27 03:04:20,201 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:04:20,205 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:04:20,206 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:12:01,788 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:12:01,887 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:12:18,737 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850507 is not handled. Duration 2 ms by bot id=6249292999"
"2024-02-27 03:12:18,739 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850507 by bot id=6249292999\nValidationError: 1 validation error for ReplyKeyboardMarkup\nkeyboard\n  Field required [type=missing, input_value={'resize_keyboard': True,...ne_time_keyboard': True}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.6/v/missing\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 270, in my_phone\n    keyboard = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/pydantic/main.py\", line 171, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\npydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup\nkeyboard\n  Field required [type=missing, input_value={'resize_keyboard': True,...ne_time_keyboard': True}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.6/v/missing"
"2024-02-27 03:12:38,244 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850508 is handled. Duration 326 ms by bot id=6249292999"
"2024-02-27 03:15:37,358 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850509 is handled. Duration 294 ms by bot id=6249292999"
"2024-02-27 03:15:46,934 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:15:46,934 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:15:46,934 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:15:50,895 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:15:50,984 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:15:54,475 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850510 is handled. Duration 257 ms by bot id=6249292999"
"2024-02-27 03:18:32,572 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:18:32,573 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:18:32,573 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:18:35,968 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:18:36,063 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:18:39,369 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850511 is handled. Duration 372 ms by bot id=6249292999"
"2024-02-27 03:18:42,372 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850512 is handled. Duration 93 ms by bot id=6249292999"
"2024-02-27 03:29:36,792 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:29:36,792 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:29:36,793 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:29:56,920 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:29:57,009 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:29:59,876 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850514 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:29:59,876 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850514 by bot id=6249292999\nValidationError: 1 validation error for ReplyKeyboardMarkup\nkeyboard\n  Field required [type=missing, input_value={'resize_keyboard': True,...ne_time_keyboard': True}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.6/v/missing\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 270, in my_phone\n    keyboard = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/pydantic/main.py\", line 171, in __init__\n    self.__pydantic_validator__.validate_python(data, self_instance=self)\npydantic_core._pydantic_core.ValidationError: 1 validation error for ReplyKeyboardMarkup\nkeyboard\n  Field required [type=missing, input_value={'resize_keyboard': True,...ne_time_keyboard': True}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.6/v/missing"
"2024-02-27 03:30:27,213 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:30:27,214 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:30:27,214 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:31:04,341 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:31:04,419 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:31:04,986 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850515 is handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:31:10,827 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850516 is handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:33:24,536 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:33:24,537 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:33:24,537 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:33:27,874 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:33:27,953 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:33:29,196 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850517 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:33:29,196 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850517 by bot id=6249292999\nAttributeError: 'NoneType' object has no attribute 'phone_number'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 270, in contact_handler\n    await message.answer(message.contact.phone_number)\nAttributeError: 'NoneType' object has no attribute 'phone_number'"
"2024-02-27 03:46:32,975 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:46:32,981 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:46:32,981 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:46:36,650 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:46:36,739 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:46:42,499 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850518 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:46:42,499 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850518 by bot id=6249292999\nAttributeError: 'NoneType' object has no attribute 'phone_number'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 274, in contact_handler\n    await message.answer(message.contact.phone_number)\nAttributeError: 'NoneType' object has no attribute 'phone_number'"
"2024-02-27 03:48:34,208 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:48:34,209 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:48:34,209 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:48:37,686 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:48:37,775 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:48:46,107 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850519 is handled. Duration 573 ms by bot id=6249292999"
"2024-02-27 03:48:48,193 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850520 is not handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:48:48,193 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850520 by bot id=6249292999\nAttributeError: 'NoneType' object has no attribute 'phone_number'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 274, in contact_handler\n    await message.answer(message.contact.phone_number)\nAttributeError: 'NoneType' object has no attribute 'phone_number'"
"2024-02-27 03:49:32,726 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:49:32,727 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:49:32,727 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:49:36,707 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:49:36,789 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:49:37,264 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850521 is handled. Duration 328 ms by bot id=6249292999"
"2024-02-27 03:49:50,736 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:49:50,737 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:49:50,737 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:49:54,345 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:49:54,447 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:49:55,459 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850522 is handled. Duration 292 ms by bot id=6249292999"
"2024-02-27 03:50:31,028 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850523 is handled. Duration 247 ms by bot id=6249292999"
"2024-02-27 03:50:36,282 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850524 is handled. Duration 94 ms by bot id=6249292999"
"2024-02-27 03:50:39,796 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850525 is handled. Duration 92 ms by bot id=6249292999"
"2024-02-27 03:50:45,376 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850526 is handled. Duration 93 ms by bot id=6249292999"
"2024-02-27 03:51:06,276 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:51:06,276 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:51:06,276 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:51:09,938 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:51:10,016 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:51:12,267 - [INFO] - STDOUT - (bot_logger.py).write(20) - message_id=4910 date=datetime.datetime(2024, 2, 26, 22, 51, 12, tzinfo=TzInfo(UTC)) chat=Chat(id=977249859, type='private', title=None, username='jasonone1337', first_name='\u041b\u0430\u0439\u043a\u0435\u0440', last_name=None, is_forum=None, photo=None, active_usernames=None, available_reactions=None, accent_color_id=None, background_custom_emoji_id=None, profile_accent_color_id=None, profile_background_custom_emoji_id=None, emoji_status_custom_emoji_id=None, emoji_status_expiration_date=None, bio=None, has_private_forwards=None, has_restricted_voice_and_video_messages=None, join_to_send_messages=None, join_by_request=None, description=None, invite_link=None, pinned_message=None, permissions=None, slow_mode_delay=None, unrestrict_boost_count=None, message_auto_delete_time=None, has_aggressive_anti_spam_enabled=None, has_hidden_members=None, has_protected_content=None, has_visible_history=None, sticker_set_name=None, can_set_sticker_set=None, custom_emoji_sticker_set_name=None, linked_chat_id=None, location=None) message_thread_id=None from_user=User(id=977249859, is_bot=False, first_name='\u041b\u0430\u0439\u043a\u0435\u0440', last_name=None, username='jasonone1337', language_code='ru', is_premium=True, added_to_attachment_menu=None, can_join_groups=None, can_read_all_group_messages=None, supports_inline_queries=None) sender_chat=None sender_boost_count=None forward_origin=None is_topic_message=None is_automatic_forward=None reply_to_message=None external_reply=None quote=None reply_to_story=None via_bot=None edit_date=None has_protected_content=None media_group_id=None author_signature=None text='\u041e\u0441\u0442\u0430\u0432\u0438\u0442\u044c \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430' entities=None link_preview_options=None animation=None audio=None document=None photo=None sticker=None story=None video=None video_note=None voice=None caption=None caption_entities=None has_media_spoiler=None contact=None dice=None game=None poll=None venue=None location=None new_chat_members=None left_chat_member=None new_chat_title=None new_chat_photo=None delete_chat_photo=None group_chat_created=None supergroup_chat_created=None channel_chat_created=None message_auto_delete_timer_changed=None migrate_to_chat_id=None migrate_from_chat_id=None pinned_message=None invoice=None successful_payment=None users_shared=None chat_shared=None connected_website=None write_access_allowed=None passport_data=None proximity_alert_triggered=None boost_added=None forum_topic_created=None forum_topic_edited=None forum_topic_closed=None forum_topic_reopened=None general_forum_topic_hidden=None general_forum_topic_unhidden=None giveaway_created=None giveaway=None giveaway_winners=None giveaway_completed=None video_chat_scheduled=None video_chat_started=None video_chat_ended=None video_chat_participants_invited=None web_app_data=None reply_markup=None forward_date=None forward_from=None forward_from_chat=None forward_from_message_id=None forward_sender_name=None forward_signature=None user_shared=None"
"2024-02-27 03:51:12,566 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850527 is handled. Duration 300 ms by bot id=6249292999"
"2024-02-27 03:56:02,246 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:56:02,249 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:56:02,249 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:56:25,525 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:56:25,612 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:56:37,964 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850528 is handled. Duration 286 ms by bot id=6249292999"
"2024-02-27 03:57:39,949 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:57:39,950 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:57:39,950 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:57:43,470 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:57:43,556 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:57:44,667 - [INFO] - STDOUT - (bot_logger.py).write(20) - sfdsffs"
"2024-02-27 03:57:44,668 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850529 is handled. Duration 0 ms by bot id=6249292999"
"2024-02-27 03:58:07,988 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 03:58:07,988 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:58:07,988 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 03:58:11,472 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 03:58:11,564 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 03:58:11,706 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850530 is not handled. Duration 1 ms by bot id=6249292999"
"2024-02-27 03:58:11,706 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850530 by bot id=6249292999\nAttributeError: 'NoneType' object has no attribute 'phone_number'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 35, in say_something\n    await message.answer(message.contact.phone_number)\nAttributeError: 'NoneType' object has no attribute 'phone_number'"
"2024-02-27 04:02:14,874 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:02:14,875 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:02:14,875 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:02:18,149 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 04:02:18,149 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 173, in <module>"
"2024-02-27 04:02:18,150 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 04:02:18,150 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 04:02:18,151 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 04:02:18,151 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 04:02:18,152 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 04:02:18,153 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 54, in start_bot"
"2024-02-27 04:02:18,153 - [ERROR] - STDERR - (bot_logger.py).write(20) - async def contact_received(message: Message, state: FSMContext):"
"2024-02-27 04:02:18,153 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 138, in wrapper"
"2024-02-27 04:02:18,154 - [ERROR] - STDERR - (bot_logger.py).write(20) - self.register(callback, *filters, flags=flags, **kwargs)"
"2024-02-27 04:02:18,154 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 68, in register"
"2024-02-27 04:02:18,154 - [ERROR] - STDERR - (bot_logger.py).write(20) - raise UnsupportedKeywordArgument("
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - aiogram.exceptions"
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - ."
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - UnsupportedKeywordArgument"
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - Passing any additional keyword arguments to the registrar method is not supported."
"2024-02-27 04:02:18,155 - [ERROR] - STDERR - (bot_logger.py).write(20) - This error may be caused when you are trying to register filters like in 2.x version of this framework, if it's true just look at correspoding documentation pages."
"2024-02-27 04:02:18,156 - [ERROR] - STDERR - (bot_logger.py).write(20) - Please remove the {'content_types'} arguments from this call."
"2024-02-27 04:02:18,156 - [ERROR] - STDERR - (bot_logger.py).write(20) - "
"2024-02-27 04:02:18,156 - [ERROR] - STDERR - (bot_logger.py).write(20) - (background on this error at: https://docs.aiogram.dev/en/dev-3.x/migration_2_to_3.html#filtering-events)"
"2024-02-27 04:02:18,254 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7fccf88fd3f0>"
"2024-02-27 04:02:18,254 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fccf89080a0>, 13880.476110237)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7fccf88fc250>"
"2024-02-27 04:03:37,598 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:03:37,686 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:03:42,403 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850531 is not handled. Duration 1 ms by bot id=6249292999"
"2024-02-27 04:03:42,403 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850531 by bot id=6249292999\nAttributeError: 'NoneType' object has no attribute 'phone_number'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 35, in say_something\n    await message.answer(message.contact.phone_number)\nAttributeError: 'NoneType' object has no attribute 'phone_number'"
"2024-02-27 04:06:35,046 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:06:35,049 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:06:35,049 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:06:38,706 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:06:38,794 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:06:41,374 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850532 is handled. Duration 262 ms by bot id=6249292999"
"2024-02-27 04:06:47,876 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850533 is handled. Duration 94 ms by bot id=6249292999"
"2024-02-27 04:07:21,679 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:07:21,680 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:07:21,680 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:07:25,255 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 04:07:25,255 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 173, in <module>"
"2024-02-27 04:07:25,256 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 04:07:25,256 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 04:07:25,257 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 04:07:25,257 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 04:07:25,258 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 04:07:25,258 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 53, in start_bot"
"2024-02-27 04:07:25,259 - [ERROR] - STDERR - (bot_logger.py).write(20) - @dp.message(ContentTypeFilter(types.ContentType.CONTACT))"
"2024-02-27 04:07:25,259 - [ERROR] - STDERR - (bot_logger.py).write(20) - NameError"
"2024-02-27 04:07:25,259 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 04:07:25,259 - [ERROR] - STDERR - (bot_logger.py).write(20) - name 'ContentTypeFilter' is not defined"
"2024-02-27 04:07:25,360 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f00ffbb5390>"
"2024-02-27 04:07:25,360 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f00ffbc0100>, 14187.581767723)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7f00ffbb4820>"
"2024-02-27 04:07:35,333 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 04:07:35,333 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 173, in <module>"
"2024-02-27 04:07:35,334 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 04:07:35,334 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 04:07:35,335 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 04:07:35,335 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 04:07:35,336 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 04:07:35,336 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 53, in start_bot"
"2024-02-27 04:07:35,336 - [ERROR] - STDERR - (bot_logger.py).write(20) - @dp.message(ContentTypeFilter(ContentType.CONTACT))"
"2024-02-27 04:07:35,337 - [ERROR] - STDERR - (bot_logger.py).write(20) - NameError"
"2024-02-27 04:07:35,337 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 04:07:35,337 - [ERROR] - STDERR - (bot_logger.py).write(20) - name 'ContentTypeFilter' is not defined"
"2024-02-27 04:07:35,437 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f267b601390>"
"2024-02-27 04:07:35,437 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f267b60c100>, 14197.659970899)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7f267b600820>"
"2024-02-27 04:09:33,563 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 04:09:33,563 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/inspect.py\", line 1277, in getfullargspec"
"2024-02-27 04:09:33,565 - [ERROR] - STDERR - (bot_logger.py).write(20) - sig = _signature_from_callable(func,"
"2024-02-27 04:09:33,565 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/inspect.py\", line 2396, in _signature_from_callable"
"2024-02-27 04:09:33,567 - [ERROR] - STDERR - (bot_logger.py).write(20) - raise TypeError('{!r} is not a callable object'.format(obj))"
"2024-02-27 04:09:33,567 - [ERROR] - STDERR - (bot_logger.py).write(20) - TypeError"
"2024-02-27 04:09:33,567 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 04:09:33,567 - [ERROR] - STDERR - (bot_logger.py).write(20) - <ContentType.CONTACT: 'contact'> is not a callable object"
"2024-02-27 04:09:33,567 - [ERROR] - STDERR - (bot_logger.py).write(20) - "
"2024-02-27 04:09:33,568 - [ERROR] - STDERR - (bot_logger.py).write(20) - The above exception was the direct cause of the following exception:"
"2024-02-27 04:09:33,568 - [ERROR] - STDERR - (bot_logger.py).write(20) - Traceback (most recent call last):"
"2024-02-27 04:09:33,568 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 173, in <module>"
"2024-02-27 04:09:33,569 - [ERROR] - STDERR - (bot_logger.py).write(20) - asyncio.run(start_bot())"
"2024-02-27 04:09:33,569 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/runners.py\", line 44, in run"
"2024-02-27 04:09:33,569 - [ERROR] - STDERR - (bot_logger.py).write(20) - return loop.run_until_complete(main)"
"2024-02-27 04:09:33,569 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete"
"2024-02-27 04:09:33,570 - [ERROR] - STDERR - (bot_logger.py).write(20) - return future.result()"
"2024-02-27 04:09:33,570 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 54, in start_bot"
"2024-02-27 04:09:33,571 - [ERROR] - STDERR - (bot_logger.py).write(20) - async def contact_received(message: Message, state: FSMContext):"
"2024-02-27 04:09:33,571 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 138, in wrapper"
"2024-02-27 04:09:33,572 - [ERROR] - STDERR - (bot_logger.py).write(20) - self.register(callback, *filters, flags=flags, **kwargs)"
"2024-02-27 04:09:33,572 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 87, in register"
"2024-02-27 04:09:33,572 - [ERROR] - STDERR - (bot_logger.py).write(20) - filters=[FilterObject(filter_) for filter_ in filters],"
"2024-02-27 04:09:33,573 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 87, in <listcomp>"
"2024-02-27 04:09:33,573 - [ERROR] - STDERR - (bot_logger.py).write(20) - filters=[FilterObject(filter_) for filter_ in filters],"
"2024-02-27 04:09:33,573 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"<string>\", line 5, in __init__"
"2024-02-27 04:09:33,574 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 72, in __post_init__"
"2024-02-27 04:09:33,574 - [ERROR] - STDERR - (bot_logger.py).write(20) - super(FilterObject, self).__post_init__()"
"2024-02-27 04:09:33,574 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 30, in __post_init__"
"2024-02-27 04:09:33,575 - [ERROR] - STDERR - (bot_logger.py).write(20) - spec = inspect.getfullargspec(callback)"
"2024-02-27 04:09:33,575 - [ERROR] - STDERR - (bot_logger.py).write(20) -   File \"/usr/lib/python3.10/inspect.py\", line 1287, in getfullargspec"
"2024-02-27 04:09:33,575 - [ERROR] - STDERR - (bot_logger.py).write(20) - raise TypeError('unsupported callable') from ex"
"2024-02-27 04:09:33,576 - [ERROR] - STDERR - (bot_logger.py).write(20) - TypeError"
"2024-02-27 04:09:33,576 - [ERROR] - STDERR - (bot_logger.py).write(20) - :"
"2024-02-27 04:09:33,576 - [ERROR] - STDERR - (bot_logger.py).write(20) - unsupported callable"
"2024-02-27 04:09:33,672 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed client session\nclient_session: <aiohttp.client.ClientSession object at 0x7f5d4b0012a0>"
"2024-02-27 04:09:33,672 - [ERROR] - asyncio - (base_events.py).default_exception_handler(1758) - Unclosed connector\nconnections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f5d4b00c100>, 14315.889537291)]']\nconnector: <aiohttp.connector.TCPConnector object at 0x7f5d4b000670>"
"2024-02-27 04:10:46,895 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:10:46,981 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:11:08,872 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850534 is handled. Duration 332 ms by bot id=6249292999"
"2024-02-27 04:11:08,874 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850535 is handled. Duration 333 ms by bot id=6249292999"
"2024-02-27 04:11:08,874 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850537 is handled. Duration 331 ms by bot id=6249292999"
"2024-02-27 04:11:08,889 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850536 is handled. Duration 347 ms by bot id=6249292999"
"2024-02-27 04:11:14,399 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850538 is handled. Duration 93 ms by bot id=6249292999"
"2024-02-27 04:11:25,211 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:11:25,211 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:11:25,212 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:11:28,619 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:11:28,706 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:11:36,376 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850539 is handled. Duration 285 ms by bot id=6249292999"
"2024-02-27 04:12:36,703 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 104] Connection reset by peer"
"2024-02-27 04:12:36,703 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6249292999)"
"2024-02-27 04:12:47,953 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6249292999)"
"2024-02-27 04:13:06,064 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:13:06,064 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:06,065 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:13:09,566 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:13:09,680 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:16,532 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850540 is handled. Duration 398 ms by bot id=6249292999"
"2024-02-27 04:13:33,259 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:13:33,260 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:33,260 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:13:36,748 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:13:36,855 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:39,564 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850541 is not handled. Duration 352 ms by bot id=6249292999"
"2024-02-27 04:13:39,564 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850541 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '!' is reserved and must be escaped with the preceding '\\'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot.py\", line 56, in contact_received\n    await message.answer(f\"\u0421\u043f\u0430\u0441\u0438\u0431\u043e! \u041c\u044b \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0438 \u0432\u0430\u0448 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430: {phone_number}\")\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '!' is reserved and must be escaped with the preceding '\\'"
"2024-02-27 04:13:50,657 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:13:50,658 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:50,658 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:13:54,138 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:13:54,259 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:13:56,249 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850542 is handled. Duration 380 ms by bot id=6249292999"
"2024-02-27 04:16:35,782 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:16:35,783 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:16:35,783 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 04:16:39,257 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 04:16:39,349 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:16:55,328 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850543 is not handled. Duration 256 ms by bot id=6249292999"
"2024-02-27 04:16:55,329 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850543 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '!' is reserved and must be escaped with the preceding '\\'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 285, in contact_handler\n    await message.answer(f\"\u0421\u043f\u0430\u0441\u0438\u0431\u043e! \u041c\u044b \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0438 \u0432\u0430\u0448 \u043d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430: {phone_number}\")\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '!' is reserved and must be escaped with the preceding '\\'"
"2024-02-27 04:22:45,645 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850544 is not handled. Duration 246 ms by bot id=6249292999"
"2024-02-27 04:22:45,645 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850544 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only"
"2024-02-27 04:22:57,745 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850545 is not handled. Duration 77 ms by bot id=6249292999"
"2024-02-27 04:22:57,745 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850545 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only"
"2024-02-27 04:24:20,322 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850546 is not handled. Duration 276 ms by bot id=6249292999"
"2024-02-27 04:24:20,322 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850546 by bot id=6249292999\nTelegramMigrateToChat: Telegram server says - Bad Request: group chat was upgraded to a supergroup chat\n(background on this error at: https://core.telegram.org/bots/api#responseparameters)\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 114, in check_response\n    raise TelegramMigrateToChat(\naiogram.exceptions.TelegramMigrateToChat: Telegram server says - Bad Request: group chat was upgraded to a supergroup chat\n(background on this error at: https://core.telegram.org/bots/api#responseparameters)"
"2024-02-27 04:24:45,843 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850547 is not handled. Duration 224 ms by bot id=6249292999"
"2024-02-27 04:24:45,843 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850547 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only"
"2024-02-27 04:25:07,994 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850548 is not handled. Duration 225 ms by bot id=6249292999"
"2024-02-27 04:25:07,994 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850548 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only"
"2024-02-27 04:25:23,352 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850549 is not handled. Duration 290 ms by bot id=6249292999"
"2024-02-27 04:25:23,352 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850549 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 40, in say_something\n    await message.answer('\u043e\u043a\u0435\u0439, \u043d\u0430\u0436\u043c\u0438 \u043a\u043d\u043e\u043f\u043a\u0443', reply_markup=main_kb1)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: phone number can be requested in private chats only"
"2024-02-27 04:27:34,311 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 04:27:34,311 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 04:27:34,312 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:01:17,596 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:01:17,680 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:01:22,067 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:01:22,068 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:01:22,068 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:01:53,091 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:01:53,183 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:01:55,710 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:01:55,710 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:01:55,710 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:02:13,833 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:02:13,910 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:02:20,938 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:02:20,939 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:02:20,939 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:02:35,880 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:02:35,960 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:02:38,394 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850557 is handled. Duration 428 ms by bot id=6249292999"
"2024-02-27 16:02:42,843 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850558 is handled. Duration 135 ms by bot id=6249292999"
"2024-02-27 16:10:03,372 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:10:03,378 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:10:03,378 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:12:14,354 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:12:14,450 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:12:17,694 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850560 is not handled. Duration 273 ms by bot id=6249292999"
"2024-02-27 16:12:17,694 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=177850560 by bot id=6249292999\nTelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'\nTraceback (most recent call last):\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 309, in _process_update\n    response = await self.feed_update(bot, update, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 158, in feed_update\n    response = await self.update.wrap_outer_middleware(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py\", line 25, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py\", line 27, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/fsm/middleware.py\", line 41, in __call__\n    return await handler(event, data)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py\", line 276, in _listen_update\n    return await self.propagate_event(update_type=update_type, event=event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 128, in propagate_event\n    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 123, in _wrapped\n    return await self._propagate_event(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/router.py\", line 148, in _propagate_event\n    response = await observer.trigger(event, **kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py\", line 121, in trigger\n    return await wrapped_inner(event, kwargs)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py\", line 43, in call\n    return await wrapped()\n  File \"/home/denis/Desktop/Projects/work/Konkrit/Konkrit_Telegram_Bot/bot_messages/bot_answer.py\", line 280, in write_manager\n    await message.answer('\u0425\u043e\u0440\u043e\u0448\u043e, \u0432\u043e\u0442 \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u043c\u0435\u043d\u0435\u0434\u0436\u0435\u0440\u0430 - \\@Vindma2903')\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/methods/base.py\", line 84, in emit\n    return await bot(self)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/bot.py\", line 492, in __call__\n    return await self.session(self, method, timeout=request_timeout)\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 254, in __call__\n    return cast(TelegramType, await middleware(bot, method))\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py\", line 178, in make_request\n    response = self.check_response(\n  File \"/home/denis/Env/Konkrit_Telegram_Bot/lib/python3.10/site-packages/aiogram/client/session/base.py\", line 120, in check_response\n    raise TelegramBadRequest(method=method, message=description)\naiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'"
"2024-02-27 16:12:26,234 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:12:26,235 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:12:26,235 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 16:12:30,112 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 16:12:30,188 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:12:34,513 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=177850562 is handled. Duration 380 ms by bot id=6249292999"
"2024-02-27 16:24:20,991 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal"
"2024-02-27 16:24:20,997 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
"2024-02-27 16:24:20,997 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped"
"2024-02-27 19:39:35,886 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling"
"2024-02-27 19:39:35,965 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @denis14101999_first_bot id=6249292999 - 'Billy_bot'"
